classification: library
org_line: Production Engineering
owners:
  - Shopify/sysperf
url: https://development.shopify.io/engineering/production/performance/profiling/
slack_channels:
  - team-sysperf
